src/Entity/Phone.php
<?php

namespace App\Entity;

use App\Repository\PhoneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PhoneRepository::class)]
class Phone
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $phone_name = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 1)]
    private ?string $price = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'phones')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product = null;

    #[ORM\ManyToMany(targetEntity: Supplier::class, inversedBy: 'phones')]
    private Collection $suppliers;

    #[ORM\OneToMany(mappedBy: 'phone', targetEntity: Sale::class, orphanRemoval: true)]
    private Collection $sales;

    public function __construct()
    {
        $this->suppliers = new ArrayCollection();
        $this->sales = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhoneName(): ?string
    {
        return $this->phone_name;
    }

    public function setPhoneName(string $phone_name): self
    {
        $this->phone_name = $phone_name;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    /**
     * @return Collection<int, Supplier>
     */
    public function getSuppliers(): Collection
    {
        return $this->suppliers;
    }

    public function addSupplier(Supplier $supplier): self
    {
        if (!$this->suppliers->contains($supplier)) {
            $this->suppliers->add($supplier);
        }

        return $this;
    }

    public function removeSupplier(Supplier $supplier): self
    {
        $this->suppliers->removeElement($supplier);

        return $this;
    }

    /**
     * @return Collection<int, Sale>
     */
    public function getSales(): Collection
    {
        return $this->sales;
    }

    public function addSale(Sale $sale): self
    {
        if (!$this->sales->contains($sale)) {
            $this->sales->add($sale);
            $sale->setPhone($this);
        }

        return $this;
    }

    public function removeSale(Sale $sale): self
    {
        if ($this->sales->removeElement($sale)) {
            // set the owning side to null (unless already changed)
            if ($sale->getPhone() === $this) {
                $sale->setPhone(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $pro_name = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Phone::class, orphanRemoval: true)]
    private Collection $phones;

    public function __construct()
    {
        $this->phones = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProName(): ?string
    {
        return $this->pro_name;
    }

    public function setProName(string $pro_name): self
    {
        $this->pro_name = $pro_name;

        return $this;
    }

    /**
     * @return Collection<int, Phone>
     */
    public function getPhones(): Collection
    {
        return $this->phones;
    }

    public function addPhone(Phone $phone): self
    {
        if (!$this->phones->contains($phone)) {
            $this->phones->add($phone);
            $phone->setProduct($this);
        }

        return $this;
    }

    public function removePhone(Phone $phone): self
    {
        if ($this->phones->removeElement($phone)) {
            // set the owning side to null (unless already changed)
            if ($phone->getProduct() === $this) {
                $phone->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/PhoneController.php
<?php

namespace App\Controller;

use App\Entity\Customer;
use App\Entity\Phone;
use App\Entity\Product;
use App\Form\AddCustomerType;
use App\Form\AddPhoneType;
use App\Repository\CustomerRepository;
use App\Repository\PhoneRepository;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PhoneController extends AbstractController
{
    #[Route('/phone', name: 'app_phone')]
    public function index(): Response
    {
        return $this->render('phone/index.html.twig', [
            'controller_name' => 'PhoneController',
        ]);
    }

    #[Route('/phone/add', name: 'app_phone_add')]
    public function addSupplierAction(Request $request, PhoneRepository $phoneRepository): Response
    {
        $phone = new Phone();

        $form = $this->createForm(AddPhoneType::class, $phone);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $phone = $form->getData();
            $phoneRepository->save($phone, true);
            $this->addFlash('success', 'Adding phone successfully!');
            return $this->redirectToRoute('app_phone_add');
        }

        return $this->render('phone/add.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/phone/all', name: 'app_phone_all')]
    public function getAllPhone(PhoneRepository $phoneRepository): Response
    {
        $phones = $phoneRepository->findAll();
        //dd($phones);
         return $this->render('phone/all.html.twig', [
             'phones' => $phones
         ]);
    }

    #[Route('/phone/{name}', name: 'app_phone_by_name')]
    public function getPhoneByName(PhoneRepository $phoneRepository, string $name): Response
    {
        $phones = $phoneRepository->getPhoneByName($name);
        return $this->render('phone/all.html.twig', [
            'phones' => $phones
        ]);
    }

    #[Route('phone/edit/{id}', name:'app_phone_edit')]
    public function editPhoneAction(Request $request,PhoneRepository $phoneRepository,Phone $phone): Response
    {
        $form = $this->createForm(AddPhoneType::class, $phone);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $phone = $form->getData();
            $phoneRepository->save($phone, true);


            $this->addFlash('success', 'Phone information has been successfully updated');
            return $this->redirectToRoute('app_phone_all');
        }

        return $this->render('phone/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/phone/delete/{id}', name: 'app_phone_delete')]
    public function deleteAction(Phone $phone, PhoneRepository $phoneRepository): Response
    {
        $phoneRepository->remove($phone, true);

        return $this->redirectToRoute('app_phone_all');
    }

    #[Route('/phone/details/{id}', name: 'app_phone_details')]
    public function customerDetails(Phone $phone): Response
    {
        return $this->render('phone/details.html.twig', [
            'phone' => $phone
        ]);
    }
}

templates/phone/add.html.twig
{% extends 'base.html.twig' %}
{% block title %}Add Phone{% endblock %}

{% block body %}
        {{ form(form) }}
{% endblock %}

templates/phone/all.html.twig
{% extends 'base.html.twig' %}

{% block title %}Phone list{% endblock %}

{% block body %}
    <h1>Phone list</h1>
        <table class="table table-striped">
            <thead>
            <tr class="text-center">
                <th scope="col">Id</th>
                <th scope="col">Phone Name</th>
                <th scope="col">Price</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for phone in phones %}
                <tr class="text-center">
                    <td>{{ phone.id }}</td>
                    <td>{{ phone.phoneName }}</td>
                    <td>{{ phone.price}}</td>
                    <td>
                        <a class="btn btn-warning" href="{{ path('app_phone_edit', {'id' :phone.id}) }}">Edit</a>
                        <a class="btn btn-danger" href="{{ path('app_phone_delete', {'id' :phone.id}) }}">Delete</a>
                        <a class="btn btn-primary" href="{{ path('app_phone_details', {'id' :phone.id}) }}">Detail</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

templates/phone/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customer detail{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-header">
            <h1>Customer detail</h1>
        </div>
        <div class="card-body">
            <p class="card-text"><span class="fs-6 fw-bold">Phone ID: </span>{{ phone.id }}</p>
            <p class="card-text"><span class="fs-6 fw-bold">Phone Name: </span>{{ phone.phoneName }}</p>
            <p class="card-text"><span class="fs-6 fw-bold">Product ID: </span>{{ phone.Product.proName }}</p>
            <p class="card-text"><span class="fs-6 fw-bold">Price: </span>{{ phone.price }}</p>
            <p class="card-text"><span class="fs-6 fw-bold">Price: </span>{{ phone.date|date('d/m/y H:i') }}</p>
        </div>
    </div>


{% endblock %}

templates/phone/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Update phone{% endblock %}

{% block body %}
    {{ form(form) }}
{% endblock %}

templates/phone/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PhoneController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/Phone_Shop/src/Controller/PhoneController.php'|file_link(0) }}">src/Controller/PhoneController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/Phone_Shop/templates/phone/index.html.twig'|file_link(0) }}">templates/phone/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}