src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $phone_number = null;

    #[ORM\OneToMany(mappedBy: 'customer', targetEntity: Sale::class, orphanRemoval: true)]
    private Collection $sales;

    public function __construct()
    {
        $this->sales = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @return Collection<int, Sale>
     */
    public function getSales(): Collection
    {
        return $this->sales;
    }

    public function addSale(Sale $sale): self
    {
        if (!$this->sales->contains($sale)) {
            $this->sales->add($sale);
            $sale->setCustomer($this);
        }

        return $this;
    }

    public function removeSale(Sale $sale): self
    {
        if ($this->sales->removeElement($sale)) {
            // set the owning side to null (unless already changed)
            if ($sale->getCustomer() === $this) {
                $sale->setCustomer(null);
            }
        }

        return $this;
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Entity\Customer;
use App\Entity\Supplier;
use App\Form\AddCustomerType;
use App\Form\AddSupplierType;
use App\Repository\CustomerRepository;
use App\Repository\SupplierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CustomerController extends AbstractController
{
    #[Route('/customer', name: 'app_customer')]
    public function index(): Response
    {
        return $this->render('customer/index.html.twig', [
            'controller_name' => 'CustomerController',
        ]);
    }

    #[Route('/customer/all', name: 'app_customer_all')]
    public function getAllCustomer(CustomerRepository $customerRepository): Response
    {
        $customers = $customerRepository->findAll();
//        dd($customers);

        return $this->render('customer/all.html.twig', [
            'customers' => $customers
        ]);
    }

    #[Route('/customer/add', name: 'app_customer_add')]
    public function addSupplierAction(Request $request, CustomerRepository $customerRepository): Response
    {
        $customer = new Customer();

        $form = $this->createForm(AddCustomerType::class, $customer);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $customer = $form->getData();
            $customerRepository->save($customer, true);
            $this->addFlash('success', 'Adding customer successfully!');
            return $this->redirectToRoute('app_customer_add');
        }

        return $this->render('customer/add.html.twig', [
            'form' => $form
        ]);
    }
    #[Route('/customer/edit/{id}', name: 'app_customer_edit')]
    public function editAction(Request $request, CustomerRepository $customerRepository, Customer $customer): Response
    {
        $form = $this->createForm(AddCustomerType::class, $customer);
        //dd($shoe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $customer = $form->getData();
            $customerRepository->save($customer, true);


            $this->addFlash('success', 'Customer information has been successfully updated');
            return $this->redirectToRoute('app_customer_all');
        }

        return $this->render('customer/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/customer/delete/{id}', name: 'app_customer_delete')]
    public function deleteAction(Customer $customer, CustomerRepository $customerRepository): Response
    {
        $customerRepository->remove($customer, true);

        return $this->redirectToRoute('app_customer_all');
    }

    #[Route('/customer/details/{id}', name: 'app_customer_details')]
    public function customerDetails(Customer $customer): Response
    {
        return $this->render('customer/details.html.twig', [
            'customer' => $customer
        ]);
    }
}

templates/customer/add.html.twig
{% extends 'base.html.twig' %}
{% block title %}Add Customer{% endblock %}

{% block body %}
        {{ form(form) }}
{% endblock %}

templates/customer/all.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customer list{% endblock %}

{% block body %}
    <h1>Customer list</h1>
        <table class="table table-striped">
            <thead>
            <tr class="text-center">
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr class="text-center">
                    <td>{{ customer.id }}</td>
                    <td>{{ customer.name }}</td>
                    <td>
                        <a class="btn btn-warning" href="{{ path('app_customer_edit', {'id': customer.id}) }}">Edit</a>
                        <a class="btn btn-danger" href="{{ path('app_customer_delete', {'id': customer.id}) }}">Delete</a>
                        <a class="btn btn-primary" href="{{ path('app_customer_details', {'id' :customer.id}) }}">Detail</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

templates/customer/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customer detail{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-header">
            <h1>Customer detail</h1>
        </div>
        <div class="card-body">
            <p class="card-text"><span class="fs-6 fw-bold">Customer ID: </span>{{ customer.id }}</p>
            <p class="card-text"><span class="fs-6 fw-bold">Customer name: </span>{{ customer.name }}</p>
            <p class="card-text"><span class="fs-6 fw-bold">Address: </span>{{ customer.address }}</p>
            <p class="card-text"><span class="fs-6 fw-bold">Phone number: </span>{{ customer.phoneNumber }}</p>
        </div>
    </div>


{% endblock %}

templates/customer/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Update Customer{% endblock %}

{% block body %}
        {{ form(form) }}
{% endblock %}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CustomerController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/Phone_Shop/src/Controller/CustomerController.php'|file_link(0) }}">src/Controller/CustomerController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/Phone_Shop/templates/customer/index.html.twig'|file_link(0) }}">templates/customer/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}