src/Entity/Supplier.php
<?php

namespace App\Entity;

use App\Repository\SupplierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SupplierRepository::class)]
class Supplier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $sup_name = null;

    #[ORM\Column]
    private ?bool $importer = null;

    #[ORM\ManyToMany(targetEntity: Phone::class, mappedBy: 'suppliers')]
    private Collection $phones;

    public function __construct()
    {
        $this->phones = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSupName(): ?string
    {
        return $this->sup_name;
    }

    public function setSupName(string $sup_name): self
    {
        $this->sup_name = $sup_name;

        return $this;
    }

    public function isImporter(): ?bool
    {
        return $this->importer;
    }

    public function setImporter(bool $importer): self
    {
        $this->importer = $importer;

        return $this;
    }

    /**
     * @return Collection<int, Phone>
     */
    public function getPhones(): Collection
    {
        return $this->phones;
    }

    public function addPhone(Phone $phone): self
    {
        if (!$this->phones->contains($phone)) {
            $this->phones->add($phone);
            $phone->addSupplier($this);
        }

        return $this;
    }

    public function removePhone(Phone $phone): self
    {
        if ($this->phones->removeElement($phone)) {
            $phone->removeSupplier($this);
        }

        return $this;
    }
}

src/Controller/SupplierController.php
<?php

namespace App\Controller;

use App\Entity\Customer;
use App\Entity\Supplier;
use App\Form\AddSupplierType;
use App\Repository\CustomerRepository;
use App\Repository\PhoneRepository;
use App\Repository\SupplierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SupplierController extends AbstractController
{
    #[Route('/supplier', name: 'app_supplier')]
    public function index(): Response
    {
        return $this->render('supplier/index.html.twig', [
            'controller_name' => 'SupplierController',
        ]);
    }

    #[Route('/supplier/add', name: 'app_supplier_add')]
    public function addSupplierAction(Request $request, SupplierRepository $supplierRepository): Response
    {
        $supplier = new Supplier();

        $form = $this->createForm(AddSupplierType::class, $supplier);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $supplier = $form->getData();
            $supplierRepository->save($supplier, true);
            $this->addFlash('success', 'Adding supplier successfully!');
            return $this->redirectToRoute('app_supplier_add');
        }

        return $this->render('supplier/add.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/supplier/all', name: 'app_supplier_all')]
    public function getAllCustomer(SupplierRepository $supplierRepository): Response
    {
        $suppliers = $supplierRepository->findAll();
//        dd($customers[0]->getPhoneNumber());

        return $this->render('supplier/all.html.twig', [
            'suppliers' => $suppliers
        ]);
    }
    #[Route('/supplier/{name}', name: 'app_supplier_by_name')]
    public function getPhoneByName(SupplierRepository $supplierRepository, string $name): Response
    {
        $suppliers = $supplierRepository->getSupplierByName($name);
        return $this->render('supplier/all.html.twig', [
            'suppliers' => $suppliers
        ]);
    }

    #[Route('/supplier/delete/{id}', name:'app_supplier_delete')]
    public function deleteFunAction(SupplierRepository $supplierRepository, Supplier $supplier):Response
    {
        $supplierRepository->remove($supplier,true);
        return $this->redirectToRoute('app_supplier_all');
    }

    #[Route('/supplier/edit/{id}', name: 'app_supplier_edit')]
    public function editFunAction(SupplierRepository $supplierRepository, Supplier $supplier, Request $request): Response
    {
        $form = $this->createForm(AddSupplierType::class, $supplier);
        $form-> handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $supplier = $form->getData();
            $supplierRepository->save($supplier, true);

            $this->addFlash('success', 'Supplier information have been update');
            return $this->redirectToRoute('app_supplier_all');
        }
        return $this->render('supplier/edit.html.twig', [
            'form' =>$form
        ]);
    }

    #[Route('/supplier/details/{id}', name: 'app_supplier_details')]
    public function supplierDetails(Supplier $supplier): Response
    {
        return $this->render('supplier/details.html.twig', [
            'supplier' => $supplier
        ]);
    }
}

templates/supplier/add.html.twig
{% extends 'base.html.twig' %}
{% block title %}Add Suppiler{% endblock %}

{% block body %}
        {{ form(form) }}
{% endblock %}

templates/supplier/all.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supplier list{% endblock %}

{% block body %}
    <h1>Supplier list</h1>
        <table class="table table-striped">
            <thead>
            <tr class="text-center">
                <th scope="col">ID</th>
                <th scope="col">Supplier Name</th>
                <th scope="col">Importer</th>
                <th scope="col">Actions</th>

            </tr>
            </thead>
            <tbody>
            {% for supplier in suppliers %}
                <tr class="text-center">
                    <td>{{ supplier.id }}</td>
                    <td>{{ supplier.supName }}</td>
                    <td>{{ supplier.importer?"Importer":"Local" }}</td>
                    <td>
                        <a class="btn btn-warning" href="{{ path('app_supplier_edit', {'id' :supplier.id}) }}">Edit</a>
                        <a class="btn btn-danger" href="{{ path('app_supplier_delete',{'id':supplier.id}) }}">Delete</a>
                        <a class="btn btn-primary" href="{{ path('app_supplier_details',{'id':supplier.id}) }}">Detail</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

templates/supplier/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customer detail{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-header">
            <h1>Customer detail</h1>
        </div>
        <div class="card-body">
            <p class="card-text"><span class="fs-6 fw-bold">Supplier ID: </span>{{ supplier.id }}</p>
            <p class="card-text"><span class="fs-6 fw-bold">Supplier name: </span>{{ supplier.supName }}</p>
            <p class="card-text"><span class="fs-6 fw-bold">Importer: </span>{{ supplier.importer }}</p>
        </div>
    </div>


{% endblock %}

templates/supplier/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Update supplier{% endblock %}

{% block body %}
    {{ form(form) }}
{% endblock %}

templates/supplier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SupplierController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/Phone_Shop/src/Controller/SupplierController.php'|file_link(0) }}">src/Controller/SupplierController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/Phone_Shop/templates/supplier/index.html.twig'|file_link(0) }}">templates/supplier/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}